name: Check codes
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4

      - name: Get pnpm version
        id: pnpm_version
        run: echo "pnpm_version=$(jq -r '.packageManager' package.json | cut -d'@' -f2)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpm_version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Prepare
        run: pnpm expo customize tsconfig.json

      - name: Run checking
        run: pnpm turbo lint type-check test
